# AntiDupe Configuration
# Color Theme: &#FF0000 (Red) for errors/warnings, &#AAFF00 (Green) for success/info

messages:
  # General Messages
  no-permission: "&#FF0000No permission."
  console-cannot-check: "&#FF0000Console cannot check items."
  hold-item: "&#FF0000Hold an item to check."
  invalid-item: "&#FF0000Invalid item."
  item-not-found: "&#FF0000Item not found."
  invalid-id-format: "&#FF0000Invalid ID format."

  # ID Command Messages
  item-id: "&#AAFF00Item ID: &#FF0000{id}"
  duplicates-warning: "&#FF0000&lWARNING:&r &#FF0000{count} potential duplicates found!"
  error-checking: "&#FF0000Error checking item."
  usage-id: "&#FF0000Usage: /id check | /id lookup <id>"

  # Lookup Messages
  original-item: "&#AAFF00Original Item &#FF0000{id} &#AAFF00created by &#AAFF00{creator}"
  no-duplicates: "&#AAFF00No duplicates found."
  duplicates-found: "&#AAFF00Found &#FF0000{count} &#FF0000duplicates:"
  duplicate-entry: "&#AAFF00• ID &#FF0000{id} &#AAFF00by &#AAFF00{creator}"
  error-lookup: "&#FF0000Error during lookup."

  # Item History Messages
  usage-item: "&#FF0000Usage: /item history [id]"
  hold-item-or-specify: "&#FF0000Hold an item or specify ID."
  no-tracking-id: "&#AAFF00Item has no tracking ID."
  console-specify-id: "&#FF0000Console must specify ID."
  error-history: "&#FF0000Error retrieving history."
  history-for-item: "&#AAFF00History for Item &#FF0000{id}"
  created-by: "&#AAFF00Created: &#AAFF00{time} &#AAFF00by &#AAFF00{creator}"
  no-actions: "&#FF0000No actions recorded."
  actions-header: "&#AAFF00Actions:"
  action-entry: "&#AAFF00• &#AAFF00{time} &#AAFF00- &#FF0000{action} &#AAFF00by &#FF0000{player}"
  more-actions: "&#AAFF00... and &#FF0000{count} &#AAFF00more actions"

  # Dupe Alert & Admin Messages
  dupe-alert: "&#FF0000&lDUPE ALERT: &r&#AAFF00{player} &#FF0000may have duped items! ID: &#FF0000{id} &#FF0000({count} duplicates)"
  debug-mode-enabled: "&#AAFF00Debug mode &#AAFF00enabled&#AAFF00. ItemIDs will appear in lore."
  debug-mode-disabled: "&#FF0000Debug mode &#FF0000disabled&#FF0000. Cleaning inventory..."
  alerts-enabled: "&#AAFF00Dupe alerts &#AAFF00enabled&#AAFF00."
  alerts-disabled: "&#FF0000Dupe alerts &#FF0000disabled&#FF0000."
  console-no-debug: "&#FF0000Console cannot use debug mode."
  console-no-alerts: "&#FF0000Console cannot toggle alerts."
  console-no-scan: "&#FF0000Console cannot scan inventories."
  console-no-clean: "&#FF0000Console cannot clean items."
  console-no-test: "&#FF0000Console cannot test items."
  player-not-found: "&#FF0000Player not found."
  scanning-inventory: "&#AAFF00Scanning {player}'s inventory..."
  scan-complete: "&#AAFF00Scan complete: &#AAFF00{tracked} &#AAFF00tracked items, &#FF0000{suspicious} &#FF0000suspicious items found."
  suspicious-item: "&#FF0000• {item} &#AAFF00(ID: {id}) - {count} duplicates"
  debug-info-removed: "&#AAFF00Debug info removed from item."
  test-results: "&#AAFF00Test Results:"
  test-item-id: "&#AAFF00Item ID: &#FF0000{id}"
  test-fingerprint: "&#AAFF00Fingerprint: &#AAFF00{fingerprint}..."
  test-no-duplicates: "&#AAFF00No duplicates found - item appears legitimate."
  test-duplicates-found: "&#FF0000&lWARNING: &r&#FF0000{count} potential duplicates found!"
  test-duplicate-entry: "&#AAFF00• ID {id} by {creator}"
  config-reloaded: "&#AAFF00Configuration reloaded successfully!"
  admin-help-header: "&#AAFF00AntiDupe Admin Commands:"
  admin-help-reload: "&#AAFF00• &#AAFF00/antidupe reload &#AAFF00- Reload configuration"
  admin-help-stats: "&#AAFF00• &#AAFF00/antidupe stats &#AAFF00- Show tracking statistics"
  admin-help-id: "&#AAFF00• &#AAFF00/id check &#AAFF00- Check item in hand"
  admin-help-lookup: "&#AAFF00• &#AAFF00/id lookup <id> &#AAFF00- Find duplicates"
  admin-help-history: "&#AAFF00• &#AAFF00/item history [id] &#AAFF00- Show item history"
  stats-header: "&#AAFF00Item Tracking Statistics:"
  stats-total: "&#AAFF00Total tracked items: &#AAFF00{total}"
  stats-top-header: "&#AAFF00Top item types:"
  stats-item-entry: "&#AAFF00• &#AAFF00{item}&#AAFF00: &#FF0000{count}"
  dupe-help-header: "&#AAFF00AntiDupe Debug Commands:"
  dupe-help-mode: "&#AAFF00• &#AAFF00/dupe mode &#AAFF00- Toggle debug mode (shows ItemIDs in lore)"
  dupe-help-alerts: "&#AAFF00• &#AAFF00/dupe alerts &#AAFF00- Toggle dupe alert notifications"
  dupe-help-scan: "&#AAFF00• &#AAFF00/dupe scan [player] &#AAFF00- Scan inventory for duplicates"
  dupe-help-clean: "&#AAFF00• &#AAFF00/dupe clean &#AAFF00- Remove debug info from held item"
  dupe-help-test: "&#AAFF00• &#AAFF00/dupe test &#AAFF00- Test dupe detection on held item"
  dupe-help-delete: "&#AAFF00• &#AAFF00/dupe delete <id> &#AAFF00- Delete all duplicate items by ID"

  # Delete Command Messages
  console-no-delete: "&#FF0000Console cannot delete items."
  delete-usage: "&#FF0000Usage: /dupe delete <id>"
  no-duplicates-to-delete: "&#AAFF00No duplicates found to delete."
  duplicates-deleted: "&#AAFF00Deleted &#FF0000{count} &#AAFF00duplicate items with ID &#FF0000{id}&#AAFF00."

  # Protection Messages
  creative-dupe-prevented: "&#FF0000Dupe attempt blocked: {action}"
  creative-dupe-blocked: "&#FF0000Creative duplication blocked!"
  packet-violation-alert: "&#FF0000⚠ PACKET ALERT: &#AAFF00{player} &#FF0000sending suspicious packets! Reason: &#AAFF00{reason}"
  machine-shulker-alert: "&#FF0000⚠ MACHINE ALERT: Shulker killed by non-player at &#AAFF00{location}"

  # AntiCheat Messages
  high-cps-detected: "&#FF0000High CPS detected: {cps} clicks/second"
  flight-not-allowed: "&#FF0000Flight is not allowed!"
  ghost-block-detected: "&#FF0000Ghost block detected - teleporting to safety"
  suspicious-movement: "&#FF0000Suspicious movement detected"
  crystal-aura-detected: "&#FF0000Crystal Aura detected - exploit blocked!"
  impossible-reach: "&#FF0000Impossible reach distance detected!"

  # Announcement Messages
  announce-usage: "&#FF0000Usage: /announce <message>"
  announcement-sent: "&#AAFF00Announcement sent to all players"

# Plugin Settings - Optimized for Performance
settings:
  # Milliseconds between tracking actions per player (higher = better performance)
  action-throttle-ms: 1000

  # Maximum number of history entries to display (lower = better performance)
  max-history-display: 5

  # Chance (1 in N) to track inventory events (higher = better performance)
  inventory-scan-chance: 50

  # Enable automatic broadcast alerts (disable for better performance)
  broadcast-alerts: true

  # Minimum number of duplicates required to trigger alert
  min-duplicates-for-alert: 2

  # Actions that should NOT trigger alerts (performance optimization)
  ignored-alert-actions:
    - "LOGIN_SCAN"
    - "DEBUG_SCAN"
    - "MOVED"
    - "PICKED_UP"
    - "DROPPED"

# Redis Configuration (Cross-Proxy Support) - Disabled by default for performance
redis:
  # Enable Redis for cross-proxy item tracking (impacts performance)
  enabled: true

  # Redis server connection details
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  timeout: 1000

  # Connection pool settings (optimized for performance)
  pool:
    max-total: 4
    max-idle: 2
    min-idle: 1

  # Data expiration settings (seconds) - shorter = better performance
  item-expire: 43200      # 12 hours (reduced from 24)
  history-expire: 259200  # 3 days (reduced from 7)
  max-history: 50         # Max history entries per item (reduced)

# Advanced Protection Settings - Minimal for performance
protection:
  # Creative Mode Protections (lightweight)
  creative-enabled: true               # Master toggle for creative protection
  notify-admins: true                  # Notify admins of violations
  log-violations: false                # Log to console (disable for performance)

  # Violation thresholds (higher = less alerts = better performance)
  max-violations: 10                   # Violations before alert
  cleanup-interval: 300                # Seconds between cleanup (5 minutes)

# AntiCheat Settings
anticheat:
  # CPS Detection
  cps-detection: true                  # Enable click-per-second detection
  max-cps: 15                         # Maximum allowed CPS

  # Crystal Aura Detection
  crystal-aura-detection: true         # Detect crystal aura exploits
  crystal-threshold: 200               # Milliseconds between crystal interactions
  crystal-violations: 3                # Violations before punishment

  # Combat Analysis
  reach-detection: true                # Detect impossible reach distances
  max-reach: 6.0                      # Maximum reach distance (blocks)

  # Movement Analysis
  movement-analysis: true              # Enable movement pattern analysis
  ghost-block-detection: true          # Detect ghost block exploitation
  flight-detection: true               # Detect unauthorized flight

  # Creative Protection
  creative-protection: true            # Enhanced creative mode protection

  # Violation Handling
  log-violations: true                 # Log violations to console
  punishment-command: ""               # Command to execute on max violations (empty = disabled)
  # Example: "tempban {player} 10m AutoCheat: {type}"